#pragma once

#define ICD_REPORT_ON_ENTER_ACTIVE_MODE  0
#define ICD_ENFORCE_SIT_SLOW_POLL_LIMIT  0
#define ICD_MAX_NOTIFICATION_SUBSCRIBERS 1
#define CHIP_CONFIG_ENABLE_ICD_LIT       0
#define CHIP_CONFIG_ENABLE_ICD_CIP       0
#define CHIP_CONFIG_ENABLE_ICD_UAT       0
