Import("env")

env.Append(
    CPPPATH=[
        Dir(".").srcnode(),
    ],
    LINT_SOURCES=[
        Dir(".").srcnode(),
    ],
    SDK_HEADERS=[
        File("js_app.h"),
        File("js_app_installer.h"),
        File("js_app_manifest.h"),
        File("js_app_registry.h"),
        File("js_app_settings.h"),
    ],
)

libenv = env.Clone(FW_LIB_NAME="js_app")
libenv.ApplyLibFlags()

sources = [
    "js_app.c",
    "js_app_installer.c",
    "js_app_manifest.c",
    "js_app_registry.c",
    "js_app_settings.c",
]

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
