name: Sync branches with upstream 
on:
  push:
    branches:
      - "*/*"

jobs:
  sync:
    name: Push branch to upstream
    runs-on: docker
    if: github.actor != '${{ vars.GH_ACTOR_USERNAME }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync with upstream
        run: |
          git remote add github "https://${{ secrets.REPO_UPSTREAM_TOKEN }}@github.com/${{ vars.REPO_UPSTREAM }}.git"
          git push --force github ${{ github.ref }}
