Import("env")

env.Append(
    CPPPATH=[
        "#/lib/netstat",
    ],
    LINT_SOURCES=[
        Dir("."),
    ],
    SDK_HEADERS=[
        File("netstat.h"),
    ],
)

libenv = env.Clone(FW_LIB_NAME="netstat")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
