Import("env")

env.Append(
    CPPPATH=[
        Dir("dhserver").srcnode(),
        Dir("mg_dns_config").srcnode(),
    ],
    LINT_SOURCES=[
        Dir(".").srcnode(),
    ],
)


libenv = env.Clone(FW_LIB_NAME="network")
libenv.ApplyLibFlags()

sources = [
    "dhserver/dhserver.c",
    "mg_dns_config/mg_dns_config.c",
]

libenv.Append(CPPPATH=[libenv.Dir(".")])

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
