#pragma once

#include <furi_hal_bus.h>
#include <furi_hal_cortex.h>
#include <furi_hal_clock.h>
#include <furi_hal_power.h>
#include <furi_hal_debug.h>
#include <furi_hal_interrupt.h>
#include <furi_hal_gpio.h>
#include <furi_hal_dma.h>
#include <furi_hal_sdmmc.h>
#include <furi_hal_resources.h>
#include <furi_hal_mpu.h>
#include <furi_hal_usb.h>
#include <furi_hal_serial_control.h>
#include <furi_hal_serial.h>
#include <furi_hal_serial_types.h>
#include <furi_hal_spi.h>
#include <furi_hal_i2c.h>
#include <furi_hal_dac.h>
#include <furi_hal_sai.h>
#include <furi_hal_random.h>
