Import("env")

env.Append(
    CPPPATH=[
        "#/lib/settings_helphers",
    ],
    LINT_SOURCES=[
        Dir("."),
    ],
    SDK_HEADERS=[
        File("settings_app_desc.h"),
        File("settings_gui_params.h"),
    ],
)

libenv = env.Clone(FW_LIB_NAME="settings_helpers")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
