Import("env")

env.Append(
    CPPPATH=[
        Dir(".").srcnode(),
    ],
    LINT_SOURCES=[
        Dir(".").srcnode(),
    ],
    SDK_HEADERS=[
        File("api_lock.h"),
        File("color.h"),
        File("crc32_calc.h"),
        File("dsp.h"),
        File("float_tools.h"),
        File("hex.h"),
        File("md5_calc.h"),
        File("property.h"),
        File("rle_encode.h"),
        File("sha256_calc.h"),
        File("strint.h"),
        File("timer.h"),
        File("value_index.h"),
    ],
)

libenv = env.Clone(FW_LIB_NAME="toolbox")
libenv.ApplyLibFlags()

sources = [
    "color.c",
    "crc32_calc.c",
    "dsp.c",
    "float_tools.c",
    "hex.c",
    "md5_calc.c",
    "property.c",
    "rle_encode.c",
    "sha256_calc.c",
    "strint.c",
    "timers.c",
    "value_index.c",
]

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
