Import("env")

env.Append(
    CPPPATH=[
        Dir(".").srcnode(),
    ],
    LINT_SOURCES=[
        Dir(".").srcnode(),
    ],
    SDK_HEADERS=[
        File("api_lock.h"),
        File("argparse.h"),
        File("color.h"),
        File("crc32_calc.h"),
        File("dsp.h"),
        File("float_tools.h"),
        File("hex.h"),
        File("md5_calc.h"),
        File("path.h"),
        File("profiler.h"),
        File("property.h"),
        File("rle_encode.h"),
        File("sha256_calc.h"),
        File("strint.h"),
        File("timer.h"),
        File("tls_config.h"),
        File("value_index.h"),
        File("http_headers.h"),
        File("get_line.h"),
    ],
)

libenv = env.Clone(FW_LIB_NAME="toolbox")
libenv.ApplyLibFlags()

sources = [
    "argparse.c",
    "color.c",
    "crc32_calc.c",
    "dsp.c",
    "float_tools.c",
    "hex.c",
    "md5_calc.c",
    "path.c",
    "profiler.c",
    "property.c",
    "rle_encode.c",
    "sha256_calc.c",
    "strint.c",
    "timers.c",
    "tls_config.c",
    "value_index.c",
    "http_headers.c",
    "get_line.c",
]

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
