Import("env")

env.AppendUnique(
    CPPPATH=[
        Dir(".").srcnode(),
    ],
)

libenv = env.Clone(FW_LIB_NAME="drivers")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
