<?xml version='1.0' encoding='UTF-8'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="pin_tool.wfm.si91x.i2s0" label="I2S0" name="I2S0" description="" version="A">
    <properties>
      <stringProperty label="Type" id="type" defaultValue="i2s0" transient="true" hidden="true" readonly="true" description=""/>
      <stringProperty label="Custom Peripheral Name" id="peripheral.name" description=""/>
    </properties>
    <propertyCategories>
      <category label="I2S0">
        <subCategory label="">
          <propertyRef refId="peripheral.name"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals>
      <signal name="SCLK"/>
      <signal name="WSCLK"/>
      <signal name="DOUT0"/>
      <signal name="DOUT1"/>
      <signal name="DIN0"/>
      <signal name="DIN1"/>
    </signals>
  </module>
</module:DocumentRoot>
