<?xml version='1.0' encoding='UTF-8'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="pin_tool.wfm.si91x.opamp3" label="OPAMP3" name="OPAMP3" description="OPAMP3 pins" version="A">
    <properties>
      <stringProperty label="Type" id="type" defaultValue="opamp3" transient="true" hidden="true" readonly="true" description=""/>
      <stringProperty label="Custom Peripheral Name" id="peripheral.name" description=""/>
    </properties>
    <propertyCategories>
      <category label="OPAMP3">
        <subCategory label="">
          <propertyRef refId="peripheral.name"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals>
      <signal name="P"/>
      <signal name="N"/>
	  <signal name="RES"/>
	  <signal name="OUT"/>
    </signals>
  </module>
</module:DocumentRoot>
