<?xml version='1.0' encoding='UTF-8'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="pin_tool.wfm.si91x.opamp1" label="OPAMP1" name="OPAMP1" description="OPAMP1 pins" version="A">
    <properties>
      <stringProperty label="Type" id="type" defaultValue="opamp1" transient="true" hidden="true" readonly="true" description=""/>
      <stringProperty label="Custom Peripheral Name" id="peripheral.name" description=""/>
    </properties>
    <propertyCategories>
      <category label="OPAMP1">
        <subCategory label="">
          <propertyRef refId="peripheral.name"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals>
      <signal name="P"/>
      <signal name="N"/>
	  <signal name="RES"/>
	  <signal name="OUT"/>
    </signals>
  </module>
</module:DocumentRoot>
