<?xml version='1.0' encoding='UTF-8'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="pin_tool.wfm.si91x.pwm_ch0" label="PWM_CH0" name="PWM_CH0" description="PWM Channel 0 pins" version="A">
    <properties>
      <stringProperty label="Type" id="type" defaultValue="pwm_ch0" transient="true" hidden="true" readonly="true" description=""/>
      <stringProperty label="Custom Peripheral Name" id="peripheral.name" description=""/>
    </properties>
    <propertyCategories>
      <category label="PWM_CH0">
        <subCategory label="">
          <propertyRef refId="peripheral.name"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals>
      <signal name="0H"/>
      <signal name="0L"/>
    </signals>
  </module>
</module:DocumentRoot>
