<?xml version='1.0' encoding='UTF-8'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="pin_tool.wfm.si91x.qei" label="QEI" name="QEI" description="" version="A">
    <properties>
      <stringProperty label="Type" id="type" defaultValue="qei" transient="true" hidden="true" readonly="true" description=""/>
      <stringProperty label="Custom Peripheral Name" id="peripheral.name" description=""/>
    </properties>
    <propertyCategories>
      <category label="QEI">
        <subCategory label="">
          <propertyRef refId="peripheral.name"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals>
      <signal name="DIR"/>
      <signal name="IDX"/>
      <signal name="PHA"/>
      <signal name="PHB"/>
    </signals>
  </module>
</module:DocumentRoot>
