Import("env")

env.Append(
    CPPPATH=[
        Dir(".").srcnode(),
    ],
    LINT_SOURCES=[
        Dir(".").srcnode(),
    ],
    SDK_HEADERS=[
        File("fetch.h"),
        File("fetch_loader.h"),
    ],
)

libenv = env.Clone(FW_LIB_NAME="fetch")
libenv.ApplyLibFlags()

sources = libenv.Glob("*.c", source=True)

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
