tags:
- name: Settings
  description: Device settings

paths:
  /api/access:
    get:
      tags:
        - Settings
      summary: Get HTTP API access over Wi-Fi configuration
      description: Get HTTP API access over Wi-Fi configuration
      operationId: getHttpAccess
      responses:
        "200":
          description: Information retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HttpAccessInfo"
    post:
      tags:
        - Settings
      summary: Set HTTP API access over Wi-Fi configuration
      description: Set HTTP API access over Wi-Fi configuration
      operationId: setHttpAccess
      parameters:
        - name: mode
          in: query
          required: true
          schema:
            type: string
            enum: ["disabled", "enabled", "key"]
          description: Access mode
          example: "key"
        - name: key
          in: query
          required: false
          schema:
            type: string
            pattern: "^[0-9]{4,10}$"
          description: Access key (4-10 digits length). Required when mode is "key".
          example: "12345678"
      responses:
        "200":
          description: Set successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "400":
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/access/tokens:
    get:
      tags:
        - Settings
      summary: List all access tokens
      description: Provides basic information all access tokens (IDs, names and timestamps)
      operationId: getAccessTokens
      responses:
        "200":
          description: Information retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessTokensInfo"
    post:
      tags:
        - Settings
      summary: Create a new access token
      description: Generates a new access token for authorization alongside the access key
      operationId: createAccessToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccessTokensCreateRequest"
      responses:
        "200":
          description: Retrieved information about access tokens
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessToken"
    delete:
      tags:
        - Settings
      summary: Revoke all access tokens
      description: Removes all access tokens all at once
      operationId: deleteAllAccessTokens
      responses:
        "200":
          description: Deleted all access tokens
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
  /api/access/tokens/{short_id}:
    delete:
      tags:
        - Settings
      summary: Revoke an access token
      description: Removes the access token with the specified short ID
      operationId: revokeAccessToken
      parameters:
        - name: short_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Deleted corresponding access token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"

  /api/name:
    get:
      tags:
        - Settings
      summary: Get current device name
      description: Get current device name
      responses:
        "200":
          description: Information retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NameInfo"

    post:
      tags:
        - Settings
      summary: Set new device name
      description: Set new device name
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NameInfo"
      responses:
        "200":
          description: New name successfully set
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "400":
          description: Invalid name parameter, or failed to store new name
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /api/display/brightness:
    get:
      tags:
        - Settings
      summary: Get display brightness
      description: Get brightness value for displays
      operationId: getDisplayBrightness
      responses:
        "200":
          description: Information retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DisplayBrightnessInfo"
    post:
      tags:
        - Settings
      summary: Set display brightness
      description: |
        Set brightness for one or both displays
      operationId: setDisplayBrightness
      parameters:
        - name: value
          in: query
          required: true
          schema:
            type: string
            pattern: "^(auto|[0-9]{1,2}|100)$"
          description: Displays brightness (0-100/auto)
          example: "50"
      responses:
        "200":
          description: Brightness set successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "400":
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /api/audio/volume:
    get:
      tags:
        - Settings
      summary: Get audio volume
      description: Get audio volume value
      operationId: getAudioVolume
      responses:
        "200":
          description: Information retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AudioVolumeInfo"
    post:
      tags:
        - Settings
      summary: Set audio volume
      description: Set audio volume value
      operationId: setAudioVolume
      parameters:
        - name: volume
          in: query
          required: true
          schema:
            type: number
          description: Audio volume (0-100)
          example: 50
        - name: silent
          in: query
          required: false
          schema:
            type: integer
            enum: [0, 1]
          description: Set volume silently (0 - play volume change sound(default), 1 - do not play sound)
          example: 1
      responses:
        "200":
          description: Volume set successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
        "400":
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

schemas:
  HttpAccessInfo:
    type: object
    properties:
      mode:
        type: string
        enum: ["disabled", "enabled", "key"]
        description: Access mode
        example: "key"
      key_valid:
        type: boolean
        description: Access key was set and is valid
        example: true

  AccessToken:
    type: object
    properties:
      short_id:
        type: string
        minLength: 8
        maxLength: 8
        description: Short ID of the access token. Matches the first 8 characters of the token.
        example: "AAMTBO0f"
      display_id:
        type: string
        minLength: 15
        maxLength: 15
        description: Long ("display") ID of the access token. Matches the first 8 characters and last 6 characters of the token.
        example: "AAMTBO0f…Wn4fID"
      name:
        type: string
        description: User-assigned name of the token
        example: "My Script Name"
      created_at:
        type: string
        description: "Unix millisecond timestamp of when the token was created. Note: it's a number in a string."
        example: "1785812863582"
      last_used_at:
        type: string
        description: "Unix millisecond timestamp of when the token was used to make any request. Note: it's a number in a string."
        example: "1785812891337"
      token:
        type: string
        description: "Full access token. Can be used in place of the access key in \"X-API-Token\" header. Only shown once when generated, never again."
        example: "AAMTBO0fvAxB5ZO8ds8bA1JofGWn4fID"

  AccessTokensInfo:
    type: object
    properties:
      tokens:
        type: array
        items:
          $ref: "#/components/schemas/AccessToken"

  AccessTokensCreateRequest:
    type: object
    properties:
      name:
        type: string
        description: Arbitrary name to differentiate this token from others
        example: "My Script Name"
    required:
      - name

  NameInfo:
    type: object
    properties:
      name:
        type: string
        minLength: 1
        maxLength: 20
        pattern: "^[a-zA-Z0-9 !()_=+;:,.?'|@#$%^&*\\[\\]{}/\\\\\"<>-]+$"
        description: Device name (letters, digits, spaces and common punctuation; no backtick or tilde)
        example: "BUSY bar"
    required:
      - name
    additionalProperties: false
    example:
      name: "BUSY bar"

  DisplayBrightnessInfo:
    type: object
    properties:
      value:
        type: string
        description: Displays brightness (0-100/auto)
        example: "auto"

  AudioVolumeInfo:
    type: object
    properties:
      volume:
        type: number
        description: Audio volume value (0-100)
        example: 50
