Import("env")

env.Append(
    CPPPATH=[
        "#/lib/settings",
    ],
    LINT_SOURCES=[
        Dir("."),
    ],
    SDK_HEADERS=[
        File("settings_app_info.h"),
    ],
)

libenv = env.Clone(FW_LIB_NAME="settings")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
