/***************************************************************************//**
 * @file
 * @brief Core application logic.
 *******************************************************************************
 * # License
 * <b>Copyright 2025 Silicon Laboratories Inc. www.silabs.com</b>
 *******************************************************************************
 *
 * SPDX-License-Identifier: Zlib
 *
 * The licensor of this software is Silicon Laboratories Inc.
 *
 * This software is provided 'as-is', without any express or implied
 * warranty. In no event will the authors be held liable for any damages
 * arising from the use of this software.
 *
 * Permission is granted to anyone to use this software for any purpose,
 * including commercial applications, and to alter it and redistribute it
 * freely, subject to the following restrictions:
 *
 * 1. The origin of this software must not be misrepresented; you must not
 *    claim that you wrote the original software. If you use this software
 *    in a product, an acknowledgment in the product documentation would be
 *    appreciated but is not required.
 * 2. Altered source versions must be plainly marked as such, and must not be
 *    misrepresented as being the original software.
 * 3. This notice may not be removed or altered from any source distribution.
 *
 ******************************************************************************/
#include "app_assert.h"
#include "sl_status.h"
#include "app.h"
#include "sl_main_init.h"

#include "app_log.h"
#include "app_assert.h"

#include "sl_btmesh_api.h"
#include "sl_bt_api.h"

#include "sl_btmesh_cmt.h"
#include "sl_btmesh_cmt_config.h"

#include "psa/crypto.h"
#include "psa/crypto_values.h"
/*******************************************************************************
 * Application Early Init
 ******************************************************************************/
void app_init_early(void)
{
  /////////////////////////////////////////////////////////////////////////////
  // Put your additional application init code here!                         //
  // This is called once before the OS is initialized if RTOS is used.       //
  // This function precedes permanent memory allocations.                    //
  /////////////////////////////////////////////////////////////////////////////
}

/**************************************************************************//**
 * Application Init.
 *****************************************************************************/
void app_init(void)
{
  // Important: This public key is generated by script/manufacturing-token/generate_keypair.py
  // and defined in btmesh_soc_empty_cmt.slcp
  uint8_t pubkey[] = SL_BTMESH_CMT_TOKEN_PUBLIC_KEY;

  uint8_t *mesh_token_data = sl_btmesh_cmt_get_token_data();

  // mesh_token_data: first 192 bytes = data, last 64 bytes = signature
  const uint8_t *data = mesh_token_data;
  const uint8_t *signature = mesh_token_data + 192;
  size_t data_len = 192;
  size_t sig_len = 64;

  // Check if the token is signed
  bool is_signed = false;
  for (size_t i = 0; i < sig_len; i++) {
    if (signature[i] != SL_BTMESH_CMT_TAG_PADDING) {
      is_signed = true;
      break;
    }
  }

  if (is_signed) {
    // Validate signature in the token
    psa_key_attributes_t key_attributes = PSA_KEY_ATTRIBUTES_INIT;
    psa_key_id_t key_id;
    psa_status_t status;
    
    psa_set_key_algorithm(&key_attributes, PSA_ALG_ECDSA(PSA_ALG_SHA_256));
    psa_set_key_type(&key_attributes, PSA_KEY_TYPE_ECC_PUBLIC_KEY(PSA_ECC_FAMILY_SECP_R1));
    psa_set_key_bits(&key_attributes, 256);
    psa_set_key_usage_flags(&key_attributes, PSA_KEY_USAGE_VERIFY_MESSAGE);
    psa_set_key_lifetime(&key_attributes, PSA_KEY_LIFETIME_VOLATILE);
    
    status = psa_import_key(&key_attributes, pubkey, sizeof(pubkey), &key_id);
    if (status != PSA_SUCCESS) {
      app_assert(status == PSA_SUCCESS, "Importing PSA public key failed: %ld" APP_LOG_NL, status);
    }
    
    status = psa_verify_message(
      key_id,
      PSA_ALG_ECDSA(PSA_ALG_SHA_256),
      data,
      data_len,
      signature,
      sig_len
      );

    psa_destroy_key(key_id);
    if (status == PSA_SUCCESS) {
      app_log_info("PSA signature verification succeeded" APP_LOG_NL);
    } else {
      app_assert(status == PSA_SUCCESS, "Verifying PSA signature failed: %ld" APP_LOG_NL, status);
    }
  } else {
    app_log_info("Token is not signed, skipping verification" APP_LOG_NL);
  }

  // Get UUID and OOB capabilities

  uuid_128 uuid = sl_btmesh_cmt_get_uuid();
  app_log_info("UUID from token: %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x" APP_LOG_NEW_LINE,
               uuid.data[0],
               uuid.data[1],
               uuid.data[2],
               uuid.data[3],
               uuid.data[4],
               uuid.data[5],
               uuid.data[6],
               uuid.data[7],
               uuid.data[8],
               uuid.data[9],
               uuid.data[10],
               uuid.data[11],
               uuid.data[12],
               uuid.data[13],
               uuid.data[14],
               uuid.data[15]);
  uuid_128 uuid_node;
  sl_status_t sc = sl_btmesh_node_get_uuid(&uuid_node);
  if (sc != SL_STATUS_OK) {
    app_log_status_error_f(sc, "Failed to get stored UUID" APP_LOG_NEW_LINE);
  } else {
    app_log_info("Stored UUID: %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x %02x" APP_LOG_NEW_LINE,
                 uuid_node.data[0],
                 uuid_node.data[1],
                 uuid_node.data[2],
                 uuid_node.data[3],
                 uuid_node.data[4],
                 uuid_node.data[5],
                 uuid_node.data[6],
                 uuid_node.data[7],
                 uuid_node.data[8],
                 uuid_node.data[9],
                 uuid_node.data[10],
                 uuid_node.data[11],
                 uuid_node.data[12],
                 uuid_node.data[13],
                 uuid_node.data[14],
                 uuid_node.data[15]);
  }

  uint8_t  output_size;
  uint16_t output_actions;
  uint8_t  input_size;
  uint16_t input_actions;

  sc = sl_btmesh_cmt_get_oob_data(&output_size,
                                  &output_actions,
                                  &input_size,
                                  &input_actions);
  if (sc != SL_STATUS_OK) {
    app_log_status_error_f(sc, "Failed to get OOB data" APP_LOG_NEW_LINE);
  } else {
    app_log_info("OOB Data: %02x %04x %02x %04x" APP_LOG_NEW_LINE,
                 output_size,
                 output_actions,
                 input_size,
                 input_actions);
  }

  /////////////////////////////////////////////////////////////////////////////
  // Put your additional application init code here!                         //
  // This is called once during start-up.                                    //
  /////////////////////////////////////////////////////////////////////////////
}

/**************************************************************************//**
 * Application Process Action.
 *****************************************************************************/
void app_process_action(void)
{
  if (app_is_process_required()) {
    /////////////////////////////////////////////////////////////////////////////
    // Put your additional application code here!                              //
    // This will run each time app_proceed() is called.                        //
    // Do not call blocking functions from here!                               //
    /////////////////////////////////////////////////////////////////////////////
  }
}

/**************************************************************************//**
 * Bluetooth stack event handler.
 * This overrides the dummy weak implementation.
 *
 * @param[in] evt Event coming from the Bluetooth stack.
 *****************************************************************************/
void sl_bt_on_event(struct sl_bt_msg *evt)
{
  switch (SL_BT_MSG_ID(evt->header)) {
    ///////////////////////////////////////////////////////////////////////////
    // Add additional event handlers here as your application requires!      //
    ///////////////////////////////////////////////////////////////////////////

    // -------------------------------
    // Default event handler.
    default:
      break;
  }
}

/**************************************************************************//**
 * Bluetooth Mesh stack event handler.
 * This overrides the dummy weak implementation.
 *
 * @param[in] evt Event coming from the Bluetooth Mesh stack.
 *****************************************************************************/
void sl_btmesh_on_event(sl_btmesh_msg_t *evt)
{
  switch (SL_BT_MSG_ID(evt->header)) {
    ///////////////////////////////////////////////////////////////////////////
    // Add additional event handlers here as your application requires!      //
    ///////////////////////////////////////////////////////////////////////////

    // -------------------------------
    // Default event handler.
    default:
      break;
  }
}

/***************************************************************************//**
 * Handling of provisionee init result
 ******************************************************************************/
void sl_btmesh_provisionee_on_init(sl_status_t result)
{
  if (SL_STATUS_OK != result) {
    app_log_status_error_f(result, "Failed to initialize node");
  } else {
    app_log_info("Node initialized successfully");
  }
}
