<?xml version='1.0' encoding='UTF-8'?>
<module:DocumentRoot xmlns:module="http://www.silabs.com/ss/hwconfig/module.ecore">
  <module id="pin_tool.efr32.bgm27.letimer" label="LETIMER" name="LETIMER" description="" version="A">
    <properties>
      <stringProperty label="Type" id="type" defaultValue="letimer" transient="true" hidden="true" readonly="true" description=""/>
      <stringProperty label="Custom Peripheral Name" id="peripheral.name" description=""/>
    </properties>
    <propertyCategories>
      <category label="LETIMER">
        <subCategory label="">
          <propertyRef refId="peripheral.name"/>
        </subCategory>
      </category>
    </propertyCategories>
    <signals>
      <signal name="OUT0"/>
      <signal name="OUT1"/>
    </signals>
  </module>
</module:DocumentRoot>
