#pragma once

#define CHIP_CONFIG_PERSIST_SUBSCRIPTIONS           1
#define CHIP_CONFIG_SUBSCRIPTION_TIMEOUT_RESUMPTION 1
#define CHIP_CONFIG_ENABLE_READ_CLIENT              1
#define CHIP_CONFIG_ENABLE_SESSION_RESUMPTION       1
