name: 'Build'

on:
  push:
    branches:
      - dev
    tags:
      - '*'
  pull_request:

env:
  FBT_GIT_SUBMODULE_SHALLOW: 0
  DEFAULT_TARGET: 21
  FBT_TOOLCHAIN_PATH: /runner/_work

jobs:
  main:
    runs-on: BsbShell
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        u5_target: [20, 21]
    outputs:
      default_target: ${{ env.DEFAULT_TARGET }}
      update_url: ${{ steps.set-url.outputs.update_url }}

    steps:
      - name: 'Wipe workspace'
        run: |
          rm -f /home/runner/.gitconfig
          find ./ -mount -maxdepth 1 -exec rm -rf {} \;

      - name: 'Checkout code'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          fetch-depth: 2
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Configure Git and LFS for submodules'
        run: |
          # Configure Git LFS
          git lfs install --skip-smudge
          
          # Set up authentication for GitHub repositories at repo level
          echo "https://x-access-token:${GH_TOKEN}@github.com" > ~/.git-credentials
          git config credential.helper 'store --file ~/.git-credentials'
          
          # Configure LFS settings
          git config lfs.transfer.maxretries 3

      - name: 'Update submodules'
        run: |
          git submodule update --init --recursive --jobs=$(nproc) scripts/toolchain fbt_layers/fbtng || (git lfs logs last && exit 1)

      - name: 'Get commit details'
        id: names
        run: |
          BUILD_TYPE='DEBUG=1 COMPACT=0'
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            TYPE="pull"
          elif [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            TYPE="tag"
          else
            TYPE="other"
          fi
          echo "event_type=$TYPE" >> $GITHUB_OUTPUT
          python3 fbt_layers/fbtng/scripts/get_env.py "--event_file=${{ github.event_path }}" "--type=$TYPE" || (cat "${{ github.event_path }}" && exit 1)
          echo "FBT_BUILD_TYPE=$BUILD_TYPE" >> $GITHUB_ENV
          echo "U5_TARGET_HW=$(echo "${{ matrix.u5_target }}" | sed 's/f//')" >> $GITHUB_ENV

      - name: 'Build update package (unsigned)'
        id: build-fw
        run: |
          source ./scripts/toolchain/fbtenv.sh
          export FBT_GIT_SUBMODULE_SHALLOW=1
          bash ./fbt U5_TARGET_HW=${U5_TARGET_HW} $FBT_BUILD_TYPE dist

      - name: 'Check for uncommitted changes'
        run: |
          git diff --exit-code

      - name: 'Copy build artifacts'
        run: |
          rm -rf artifacts
          mkdir -p artifacts
          cp -v dist/f${U5_TARGET_HW}-*/* artifacts/

      - name: 'Calculate hashsums for artifacts'
        working-directory: artifacts
        run: |
          find . -type f -exec sha256sum {} \; > sha256sum_f${U5_TARGET_HW}.txt

      - name: 'Upload build artifacts'
        if: ${{ !github.event.pull_request.head.repo.fork && steps.build-fw.outcome == 'success' }}
        id: build-update
        run: |
          FILES=$(for ARTIFACT in $(find artifacts -maxdepth 1 -not -type d); do echo "-F files=@${ARTIFACT}"; done)
          curl --fail -L -H "Token: ${{ secrets.INDEXER_TOKEN }}" \
              -F "branch=${BRANCH_NAME}" \
              -F "version_token=${COMMIT_SHA}" \
              ${FILES[@]} \
              "${{ secrets.INDEXER_URL }}"/busybar-firmware/uploadfiles

      - name: Handle u5 map files
        if: ${{ !github.event.pull_request.head.repo.fork && steps.build-fw.outcome == 'success'  && matrix.u5_target == env.DEFAULT_TARGET}}
        run: |
          rm -rf map_analyser_files
          mkdir -p map_analyser_files
          mv -v fbt_layers/fbtng/build/f${U5_TARGET_HW}-firmware*/fw_elf/*.elf* map_analyser_files
          rm -f fbt_layers/fbtng/build/f${U5_TARGET_HW}-updater*/fw_elf/*.elf*
          source scripts/toolchain/fbtenv.sh
          python3 scripts/map_analyse_upload.py \
              "--elf_file=map_analyser_files/firmware.elf" \
              "--map_file=map_analyser_files/firmware.elf.map" \
              "--analyser_url=${{ secrets.U5_ANALYSER_URL }}" \
              "--analyser_token=${{ secrets.U5_ANALYSER_TOKEN }}";

      - name: Handle silabs map files
        if: ${{ !github.event.pull_request.head.repo.fork && steps.build-fw.outcome == 'success' && matrix.u5_target == env.DEFAULT_TARGET }}
        run: |
          rm -rf map_analyser_files
          mkdir -p map_analyser_files
          mv -v fbt_layers/fbtng/build/*/fw_elf/*.elf* map_analyser_files
          source scripts/toolchain/fbtenv.sh
          python3 scripts/map_analyse_upload.py \
              "--elf_file=map_analyser_files/firmware.elf" \
              "--map_file=map_analyser_files/firmware.elf.map" \
              "--analyser_url=${{ secrets.SIL_ANALYSER_URL }}" \
              "--analyser_token=${{ secrets.SIL_ANALYSER_TOKEN }}";

      - name: 'Find previous comment'
        if: ${{ !github.event.pull_request.head.repo.fork && matrix.u5_target == env.DEFAULT_TARGET && github.event.pull_request }}
        uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Compiled f${{ matrix.u5_target }} firmware for commit'

      - name: 'Create or update comment'
        if: ${{ !github.event.pull_request.head.repo.fork && matrix.u5_target == env.DEFAULT_TARGET && github.event.pull_request }}
        uses: peter-evans/create-or-update-comment@v4
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            **Compiled f${{ matrix.u5_target }} firmware for commit `${{steps.names.outputs.commit_sha}}`:**
            - [📦 Update package](https://update.flipperzero.one/builds/busybar-firmware/${{steps.names.outputs.branch_name}}/busybar-f${{matrix.u5_target}}-update-${{steps.names.outputs.suffix}}.tar)
            - [📊 Sil Size report](https://fw-reports-sil-bsb.flipp.dev/?branch=${{steps.names.outputs.branch_name}})
            - [📊 U5 Size report](https://fw-reports-bsb.flipp.dev/?branch=${{steps.names.outputs.branch_name}})
          edit-mode: replace

      - name: 'Set update URL output for default target'
        id: set-url
        if: ${{ matrix.u5_target == env.DEFAULT_TARGET }}
        run: |
          echo "update_url=${{ steps.names.outputs.branch_name }}/busybar-f${{ matrix.u5_target }}-update-${{ steps.names.outputs.suffix }}.tar" >> "$GITHUB_OUTPUT"


  updater-tests:
    needs: main
    if: ${{ needs.main.result == 'success' && needs.main.outputs.update_url != '' }}
    uses: './.github/workflows/updater-test.yml'
    with:
      branch_name: ${{ github.head_ref || github.ref_name }}
      commit_sha: ${{ github.sha }}
      update_url: ${{ needs.main.outputs.update_url }}
      default_target: ${{ needs.main.outputs.default_target }}
