name: 'Build'

on:
  push:
    branches:
      - dev
    tags:
      - '*'
  pull_request:

env:
  FBT_GIT_SUBMODULE_SHALLOW: 0

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        u5_target: [20, 21]
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          fetch-depth: 2
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Update submodules'
        run: |
          git submodule update --init --recursive --jobs=$(nproc) scripts/toolchain lib/lwip lib/matter_ext || cat /home/runner/work/bsb-firmware/bsb-firmware/.git/modules/lib/matter_ext/lfs/logs/*

      - name: 'Get commit details'
        id: names
        run: |
          git submodule update --init fbt_layers/fbtng
          BUILD_TYPE='DEBUG=1 COMPACT=0'
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            TYPE="pull"
          elif [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            TYPE="tag"
            # BUILD_TYPE='DEBUG=0 COMPACT=1' # TODO: To be enabled later
          else
            TYPE="other"
          fi
          echo "event_type=$TYPE" >> $GITHUB_OUTPUT
          python3 fbt_layers/fbtng/scripts/get_env.py "--event_file=${{ github.event_path }}" "--type=$TYPE" || cat "${{ github.event_path }}"
          echo "FBT_BUILD_TYPE=$BUILD_TYPE" >> $GITHUB_ENV
          echo "U5_TARGET_HW=$(echo "${{ matrix.u5_target }}" | sed 's/f//')" >> $GITHUB_ENV

      - name: 'Build update package (unsigned)'
        id: build-fw
        run: |
          source ./scripts/toolchain/fbtenv.sh
          export FBT_GIT_SUBMODULE_SHALLOW=1
          bash ./fbt U5_TARGET_HW=${U5_TARGET_HW} $FBT_BUILD_TYPE dist

      - name: 'Check for uncommitted changes'
        run: |
          git diff --exit-code

      - name: 'Copy build artifacts'
        run: |
          rm -rf artifacts
          mkdir -p artifacts
          cp -v dist/f${U5_TARGET_HW}-*/* artifacts/

      - name: 'Upload build artifacts'
        if: ${{ !github.event.pull_request.head.repo.fork }}
        id: build-update
        run: |
          FILES=$(for ARTIFACT in $(find artifacts -maxdepth 1 -not -type d); do echo "-F files=@${ARTIFACT}"; done)
          echo curl --fail -L -H "Token: ${{ secrets.INDEXER_TOKEN }}" \
              -F "branch=${BRANCH_NAME}" \
              -F "version_token=${COMMIT_SHA}" \
              ${FILES[@]} \
              "${{ secrets.INDEXER_URL }}"/busybar-firmware/uploadfiles
