name: 'Check submodule integrity'

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  SET_GH_OUTPUT: 1

jobs:
  check_submodules:
    runs-on: BsbShell
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: 'Wipe workspace'
        run: |
          rm -f /home/runner/.gitconfig
          find ./ -mount -maxdepth 1 -exec rm -rf {} \;

      - name: 'Checkout code'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Fetch submodules'
        run: |
          git submodule update --init

      - name: 'Check submodule branches'
        run: |
          bash scripts/check-submodules.sh
