name: "Compact build"

on:
  push:
    branches:
      - dev
  pull_request:

env:
  FBT_GIT_SUBMODULE_SHALLOW: 0
  DEFAULT_TARGET_SPEC: 21_64
  FBT_TOOLCHAIN_PATH: /runner/_work

jobs:
  compact-build:
    runs-on: BsbShell
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        target_spec: ["21_64", "22_65"]
    outputs:
      default_target_spec: ${{ env.DEFAULT_TARGET_SPEC }}

    steps:
      - name: "Wipe workspace"
        run: |
          find ./ -mount -maxdepth 1 -exec rm -rf {} \;

      - name: "Configure targets"
        id: targets
        run: |
          U5_TARGET=$(echo "${{ matrix.target_spec }}" | cut -d_ -f1 | sed 's/f//')
          SIL_TARGET=$(echo "${{ matrix.target_spec }}" | cut -d_ -f2 | sed 's/f//')
          echo "U5_TARGET_HW=${U5_TARGET}" >> $GITHUB_ENV
          echo "SIL_TARGET_HW=${SIL_TARGET}" >> $GITHUB_ENV
          echo "u5_target_hw=${U5_TARGET}"  >> $GITHUB_OUTPUT
          echo "sil_target_hw=${U5_TARGET}"  >> $GITHUB_OUTPUT

      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 2
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Update submodules"
        run: |
          git submodule update --init --recursive --jobs=$(nproc) scripts/toolchain fbt_layers/fbtng

      - name: "Build update package (unsigned)"
        id: build-fw
        run: |
          source ./scripts/toolchain/fbtenv.sh
          export FBT_GIT_SUBMODULE_SHALLOW=1
          bash ./fbt U5_TARGET_HW=${U5_TARGET_HW} SIL_TARGET_HW=${SIL_TARGET_HW} $FBT_BUILD_TYPE dist

      - name: "Check for uncommitted changes"
        run: |
          git diff --exit-code
