name: Sync with dev mirror
on:
  push:
    branches:
      - dev
      - hedger/*
  workflow_dispatch:

jobs:
  sync:
    name: Sync with dev mirror
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync with dev mirror
        id: sync
        run: |
          echo "Pushing changes to Forgejo mirror"
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add forgejo "https://${{ secrets.REPO_MIRROR_TOKEN }}@${{ vars.REPO_MIRROR_URL }}"
          git push forgejo ${{ github.ref }}
