name: Build frontend, check output bundle diff
on:
  push:
    branches:
      - dev
    tags:
      - "*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy frontend assets to working directory
        run: |
          mkdir -p ci_build
          cp -r ./assets/frontend/* ci_build/

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
       
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache-dependency-path: assets/frontend/pnpm-lock.yaml
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./ci_build

      - name: Build frontend
        run: pnpm run build/ci
        working-directory: ./ci_build

      - name: Check output bundle diff
        run: |
          echo "Build ID: $(git rev-parse HEAD^)"
          diff -r ./.output/public ../assets/frontend/.output/public || (echo "Output bundle has changed. Please review the changes." && exit 1)
        working-directory: ./ci_build