name: 'Unit tests'

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
      commit_sha:
        required: true
        type: string
      update_url:
        required: true
        type: string
      target:
        required: false
        type: string
        default: '21'

permissions:
  contents: read
  checks: write

env:
  U5_HW_TARGET: ${{ inputs.target }}
  FBT_GIT_SUBMODULE_SHALLOW: 0
  FBT_TOOLCHAIN_PATH: /runner/_work

jobs:
  unit-tests:
    runs-on: BusyBarTest
    steps:
      - name: 'Checkout code at the build’s commit'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha }}
          fetch-depth: 2

      - name: 'Update submodules'
        run: |
          git submodule update --init --recursive --jobs=$(nproc) scripts/toolchain fbt_layers/fbtng

      - name: 'Download unit test package'
        run: |
          set -euo pipefail
          URL="https://update.flipperzero.one/builds/busybar-firmware/${{ inputs.update_url }}"
          echo "Using URL: $URL"
          curl --fail -L -o busybar-f${{ inputs.target }}-unittests.zip "$URL"
          unzip -q busybar-f${{ inputs.target }}-unittests.zip -d unittests
          cd unittests && mkdir -p update_bundle
          tar -xf busybar-f${{ inputs.target }}-update-unittests.tar -C update_bundle

      - name: 'Flash firmware'
        id: flashing
        timeout-minutes: 20
        run: |
          set -euo pipefail
          source scripts/toolchain/fbtenv.sh
          python3 scripts/testops.py format --no-confirm
          python3 scripts/storage.py -p 10.0.4.20 send unittests/update_bundle /ext/tmp/upd_bundle
          python3 scripts/testops.py update-bundle /ext/tmp/upd_bundle/update.json
          python3 scripts/testops.py wait -t 280

      - name: 'Check that both cores are available (post-flash)'
        if: steps.flashing.outcome == 'success'
        run: |
          set -euo pipefail
          source scripts/toolchain/fbtenv.sh
          python3 scripts/testops.py sanity

      - name: 'Run units'
        timeout-minutes: 2
        run: |
          set -euo pipefail
          source scripts/toolchain/fbtenv.sh
          python3 scripts/testops.py unit-tests
