name: 'Updater tests'

on:
  repository_dispatch:
    types: [run-updater-tests]

permissions:
  contents: read

env:
  DEFAULT_TARGET: ${{ github.event.client_payload.default_target }}

jobs:
  run_units_on_bench:
    runs-on: BusyBarTest
    steps:
      - name: Checkout code at the build’s commit
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.client_payload.sha }}
          fetch-depth: 2

      - name: Update submodules
        run: |
          git submodule update --init --recursive --jobs=$(nproc) scripts/toolchain fbt_layers/fbtng

      - name: Download update package
        run: |
          set -euo pipefail
          URL="${{ github.event.client_payload.update_url }}"
          echo "Using URL: $URL"
          curl --fail --retry 6 --retry-all-errors -L -o "busybar-f${DEFAULT_TARGET}-update.tar" "$URL"
          mkdir -p update_bundle
          tar -xf "busybar-f${{ env.DEFAULT_TARGET }}-update.tar" -C update_bundle

      - name: Flash firmware
        id: flashing
        timeout-minutes: 20
        run: |
          set -euo pipefail
          source scripts/toolchain/fbtenv.sh
          python3 scripts/storage.py -p 10.0.4.20 send update_bundle /ext/tmp/upd_bundle
          expect -c 'spawn telnet 10.0.4.20 23; expect ">:"; send "update install /ext/tmp/upd_bundle/update.json\r\r"; interact'
          sleep 1
          python3 scripts/testops.py wait -t 240

      - name: Update to the firmware from PR
        id: updating
        if: steps.flashing.outcome == 'success'
        timeout-minutes: 20
        run: |
          set -euo pipefail
          source scripts/toolchain/fbtenv.sh
          python3 scripts/storage.py -p 10.0.4.20 send update_bundle /ext/tmp/upd_bundle
          expect -c 'spawn telnet 10.0.4.20 23; expect ">:"; send "update install /ext/tmp/upd_bundle/update.json\r\r"; interact'
          sleep 1
          python3 scripts/testops.py wait -t 240
