name: 'Updater tests'

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
      commit_sha:
        required: true
        type: string
      update_url:
        required: false
        type: string
      target:
        required: false
        type: string
        default: '21'

permissions:
  contents: read

env:
  U5_HW_TARGET: ${{ github.event.inputs.target }}

jobs:
  updater-test:
    runs-on: BusyBarTest
    steps:
      - name: 'Checkout code at the build’s commit'
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit_sha }}
          fetch-depth: 2

      - name: 'Update submodules'
        run: |
          git submodule update --init --recursive --jobs=$(nproc) scripts/toolchain fbt_layers/fbtng

      - name: 'Download update package'
        run: |
          set -euo pipefail
          URL="https://update.flipperzero.one/builds/busybar-firmware/${{ inputs.update_url }}"
          echo "Using URL: $URL"
          curl --fail -L -o busybar-f${{ env.U5_HW_TARGET }}-update.tar "$URL"
          mkdir -p update_bundle
          tar -xf busybar-f${{ env.U5_HW_TARGET }}-update.tar -C update_bundle

      - name: 'Flash firmware'
        id: flashing
        timeout-minutes: 20
        run: |
          set -euo pipefail
          source scripts/toolchain/fbtenv.sh
          python3 scripts/testops.py format --no-confirm
          python3 scripts/storage.py -p 10.0.4.20 send update_bundle /ext/tmp/upd_bundle
          python3 scripts/testops.py update-bundle /ext/tmp/upd_bundle/update.json
          python3 scripts/testops.py wait -t 260

      - name: 'Check that both cores are available (post-flash)'
        if: steps.flashing.outcome == 'success'
        run: |
          set -euo pipefail
          source scripts/toolchain/fbtenv.sh
          python3 scripts/testops.py sanity

      - name: 'Update again to PR firmware'
        id: updating
        if: steps.flashing.outcome == 'success'
        timeout-minutes: 20
        run: |
          set -euo pipefail
          source scripts/toolchain/fbtenv.sh
          python3 scripts/storage.py -p 10.0.4.20 send update_bundle /ext/tmp/upd_bundle
          python3 scripts/testops.py update-bundle /ext/tmp/upd_bundle/update.json
          python3 scripts/testops.py wait -t 260

      - name: 'Check that both cores are available (post-update)'
        if: steps.updating.outcome == 'success'
        run: |
          set -euo pipefail
          source scripts/toolchain/fbtenv.sh
          python3 scripts/testops.py sanity

      - name: 'Upload runner logs'
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: runner-logs-updater-test
          path: /opt/logs/${{ runner.name }}/latest/runlog.log
          if-no-files-found: warn